### ISSUE TITLE
Angular 2+ (Vortragsreihe)

### ISSUE THREAD

**Issue by gernsdorfer** [ChemnitzerWebDevs/slides#12]
## Talk description
(Please also name frameworks that you promote/use in your talk.)

Ein Vortragsreihe über mehrere Meetups zum Thema Angular 2+

* Angular Basics (Doodle: Angular 2+ Basics - Frank Strieter)
  * Aufbau 
  * Routing + Lazy Routes
  * HttpClient (Grundlagen, Interceptors, Echtzeitdaten mit Server Sent Events)
  * CLI
  * Tests
* RxJs mit NgRx (Redux) und Effects (redux Observable)
  * RxJs Basics
  * Lettable Operators
  * NgRx Integration
  * wie nutzte ich Effects
* Angular und progressiv web app (PWA)
  * Einbau und Konfiguration der Service Worker
* Angular Universal (Server Side Rendering)
  * Einrichten einer Universal app
  * Grenzen einer Universal app
* Angular & IONIC | NativeScript
* SEO mit SPAs

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [ ] No, thanks.

## Preferred date/time

- ...

## Speaker names
(Please name all speakers giving this talk.)

- Lars Wiedemann
- Frank Strieter

## Speakers info
(Optional)

- Lars Wiedemann, skriptfabrik GmbH, Frontend Developer
- Frank Strieter, co-IT.eu GmbH, Web Developer

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @gernsdorfer
- @FrankStrieter

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://twitter.com/gernsdorfer
- https://twitter.com/FrankStrieter

**Comment by Strulle** [comment]
Hier noch ein Paar Ergänzungen von mir:
* Angular Basics
** HttpClient (Grundlagen, Interceptors, Echtzeitdaten mit Server Sent Events)
* RxJs
** Lettable Operators
* Angular & IONIC | NativeScript
* SEO mit SPAs

**Comment by schroedan** [comment]
Since there is nothing more happening here in the thread, I will close it. Feel free to open a new talk proposal issue. Thank you.
