### ISSUE TITLE
Wetterdaten für Nerds: Netatmo + Grafana

### ISSUE THREAD

**Issue by schroedan** [ChemnitzerWebDevs/slides#28]
## Talk description
(Please also name frameworks that you promote/use in your talk.)

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [ ] No, thanks.

## Preferred date/time

- ...

## Speaker names
(Please name all speakers giving this talk.)

- Morris Jobke

## Speakers info
(Optional)

- Nextcloud GmbH, Web Developer

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @MorrisJobke

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://twitter.com/MorrisJobke

**Comment by MorrisJobke** [comment]
I would like to withdraw this proposal 😉

**Comment by schroedan** [comment]
Hi @MorrisJobke, thank you for replying. Just leave your changes as a comment to this issue or create a new issue here: https://github.com/ChemnitzerWebDevs/slides/issues/new

**Comment by MorrisJobke** [comment]
> I would like to withdraw this proposal 😉

This is my comment 😉 And as I can't close the ticket here I would like to ask you to do so.

**Comment by schroedan** [comment]
Okay. Too bad.
