### ISSUE TITLE
Continuous Integration mit Drone - Was ist CI? Und wie nutze ich Drone CI?

### ISSUE THREAD

**Issue by schroedan** [ChemnitzerWebDevs/slides#29]
## Talk description
(Please also name frameworks that you promote/use in your talk.)

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [ ] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [ ] No, thanks.

## Preferred date/time

- ...

## Speaker names
(Please name all speakers giving this talk.)

- Morris Jobke

## Speakers info
(Optional)

- Nextcloud GmbH, Web Developer

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @MorrisJobke

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://twitter.com/MorrisJobke

**Comment by ronnyhartenstein** [comment]
Hey @MorrisJobke & @schroedan, its done :)

**Comment by martinkutter** [comment]
Sure, see the slides here: https://github.com/ChemnitzerWebDevs/slides/blob/master/2019/04-April/Continuous%20Integration%20with%20Drone%20CI.pdf
