### ISSUE TITLE
Massig Fotos und Videos sinnvoll archivieren

### ISSUE THREAD

**Issue by schroedan** [ChemnitzerWebDevs/slides#30]
## Talk description
I'm using Nextcloud. I take a lot of photos and videos. I don't want to sync this big raw files. I want to have a smaller web-version to share it efficent. I need a tool which works automatically on new files, so I wrote (of course!) my own with PHP using some neat helpers. By the way, the quality is good enough for a 2nd slim archive or backup.

## Talk length (in Minutes)

- [x] Lightning talk (20-30 Minutes)
- [ ] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- ...

## Speaker names

- Ronny Hartenstein

## Speakers info

- axilaris GmbH, Web Developer, Team Lead

## Twitter handle(s)

- @rhflow_de

## Other links

- https://blog.rh-flow.de
- https://twitter.com/rhflow_de

**Comment by ronnyhartenstein** [comment]
> ## Talk description
I'm using Nextcloud. I take a lot of photos and videos. I don't want to sync this big raw files. I want to have a smaller web-version to share it efficent. I need a tool which works automatically on new files, so I wrote (of course!) my own. By the way, the quality is good enough for a 2nd slim archive or backup.
> 
> ## Talk length (in Minutes)
* [x]  Lightning talk (20-30 Minutes)
> * [ ]  Main talk (45-60 Minutes)
> 
> ## Preferred language
* [x]  German
> * [ ]  English
> 
> ## Talk preparation
> 
> * [ ]  Yes, ...
* [x]  No, thanks.
> 
> 
> ## Speaker names
> 
> * Ronny Hartenstein
> 
> ## Speakers info
> 
* axilaris GmbH, Web Developer, Team Lead
> 
> ## Twitter handle(s)
> 
> * @rhflow_de
> 
> ## Other links
> 
* https://blog.rh-flow.de
> * https://twitter.com/rhflow_de
