### ISSUE TITLE
Vue.js in the wild

### ISSUE THREAD

**Issue by deepDiverPaul** [ChemnitzerWebDevs/slides#41]
## Talk description

In diesem Vortrag möchte ich typische Anwendungsfälle für Vue.js. zeigen. Es sollen die positiven aber auch die kritischen Eigenschaften beleuchtet werden. Ich freue mich dieses Framework als Alternative zu Angular und React vorzustellen.

In this presentation I would like to show typical use cases for Vue.js. The positive but also the critical properties will be highlighted. I am happy to present this framework as an alternative to Angular and React. 

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] either
- [ ] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x] Yes, maybe look over my slides before the event
- [ ] No, thanks.

## Preferred date/time

- 30.01.2020

## Speaker names
(Please name all speakers giving this talk.)

- Paul Spenke

## Speakers info

- Web Developer at mailingwork

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- ¯\\\_(ツ)_/¯

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://github.com/deepDiverPaul

**Comment by MorrisJobke** [comment]
Nice - an update to mine from June 2018: https://github.com/ChemnitzerWebDevs/slides#june \o/

https://github.com/ChemnitzerWebDevs/slides/blob/master/2018/06-June/Presentation.pdf

**Comment by MorrisJobke** [comment]
🚀

**Comment by martinkutter** [comment]
Thank you very much for the proposal. Your talk is accepted!
I will announce the talk on the meetup today.
@deepDiverPaul please provide a teaser photo of you or your talk/slides, so we can share it on meetup, facebook and twitter.

**Comment by martinkutter** [comment]
Closing. Talk at 30th january.
