### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by Rambarz** [ChemnitzerWebDevs/slides#44]
## Talk description
GraphQL - API Revolution mit Hindernissen
Grundsätzliches Verständnis von GraphQL Ansätzen von Client bis Datenbank

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

Februar 2020, falls noch kein Thema dazu besteht

## Speaker names

Florian Hahn

## Speakers info
(Optional)

TU Chemnitz, Wissenschaftlicher Mitarbeiter

**Comment by martinkutter** [comment]
Nochmals Danke für deinen Vorschlag, würde bei dir auch der 26. März oder 30. April passen?

**Comment by Rambarz** [comment]
Natürlich, kein Problem, je nachdem wann es bei euch passt in die Planung.

**Comment by martinkutter** [comment]
Wie sieht es bei dir am 26. März aus, bleibt es dabei?

**Comment by Rambarz** [comment]
Können wir machen, dann bereite ich die Folien vor.

**Comment by martinkutter** [comment]
Super, von uns aus kannst du dir übrigens aussuchen, welchen deiner Vorträge du halten möchtest. Kannst du an deiner Beschreibung bitte noch ein Bild ergänzen, dass ich als Teaser zum ankündigen des Meetups nehmen kann. Danke.

**Comment by schroedan** [comment]
Since there is nothing more happening here in the thread, I will close it. Feel free to open a new talk proposal issue. Thank you.
