### ISSUE TITLE
Integrationsplattform

### ISSUE THREAD

**Issue by Rambarz** [ChemnitzerWebDevs/slides#45]
## Talk description
Integrationsplattform - iPaaS in Unternehmen zur Entkopplung von IT Landschaften

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

Februar 2020, falls noch kein Thema dazu besteht

## Speaker names

Florian Hahn

## Speakers info
(Optional)

TU Chemnitz, Wissenschaftlicher Mitarbeiter

**Comment by martinkutter** [comment]
@Rambarz kannst du bitte noch eine ausführlichere Beschreibung ergänzen und welche Termine (letzte Donnerstage im Monat) dir passen würden? Vielen Dank 😊

**Comment by martinkutter** [comment]
@Rambarz Reminder

**Comment by schroedan** [comment]
Since there is nothing more happening here in the thread, I will close it. Feel free to open a new talk proposal issue. Thank you.
