### ISSUE TITLE
Künstliche Intelligenz im Browser?!

### ISSUE THREAD

**Issue by audoryio** [ChemnitzerWebDevs/slides#46]
## Talk description
(Please also name frameworks that you promote/use in your talk.)

**Titel**
Künstliche Intelligenz im Browser?!
Wie auch du diese Technologie **ohne tiefes Verständnis** nutzen kannst.

**Aufbau**
- Grundlagen Neuronale Netze
  - Aufbau/Funktion eines Neurons
  - Architektur von Neuronalen Netzen
- Training von Neuronalen Netzen
  - Daten sammeln & aufbereiten
  - Architektur designen
  - Model trainieren/testen
- [Praxis] Umsetzung mit Tensorflow.js
  - Vorstellung Tensorflow.js
  - Teachable Machine Live Demo
- Ausblick
  - Weitere Projektideen
- Diskussion

Für den Talk verwende ich die Machine learning Bibliothek [Tensorflow.js](https://www.tensorflow.org/js).

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 27.02.2020

## Speaker names
(Please name all speakers giving this talk.)

- Max Rose

## Speakers info
(Optional)

- Max Rose, audory, Gründer

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @webdevchem

## Other links
(Optional, Blog, github, medium, facebook, etc.)

- https://audory.io

**Comment by martinkutter** [comment]
@audoryio please „solve“ this issue by creating a pull request with your slides. 🍪

**Comment by martinkutter** [comment]
Resolved with #48
