### ISSUE TITLE
Generic backend visions

### ISSUE THREAD

**Issue by guettli** [ChemnitzerWebDevs/slides#49]
## Generic Backend Vision

Sooner or later the generic backend vision will become reality. No more custom coding in the backend.

No more if-ing and loop-ing. No more imperative programming in the backend.

But if you don't need to write "if ... else ..." and "for .. in ... do ..." what do you write?

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x] Yes. I am not a native speaker, and I guess there are some typos in my text. It would be very kind if someone could have a lot at github README and provide feedback.
- [ ] No, thanks.

## Preferred date/time

- any time

## Speaker names

Thomas Güttler

## Speakers info

- Scrum Master at [Staffbase](https://staffbase.com/)

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @webdevchem

## Other links

- Talk: https://github.com/guettli/generic-backend-vision

**Comment by schroedan** [comment]
Hi @guettli

Please help me. Had you already given the talk to the audience? Otherwise, does your proposal still exist?

**Comment by guettli** [comment]
@schroedan thank you for asking. The topic is still on my mind, but I have not found enough valuable stuff to talk about. I close this.
