### ISSUE TITLE
JavaScript zum Anfassen

### ISSUE THREAD

**Issue by deepDiverPaul** [ChemnitzerWebDevs/slides#51]
## Talk description

Hardware und Webdeveloper? In dem Talk möchte ich gern Espruino vorstellen. Das Projekt bringt JavaScript auf die Microcontroller und ermöglicht es mit geringem Aufwand verschiedenste Projekte umzusetzen. Es ist nicht nur für Bastler interessant, sondern bringt auch 'fertige' Komponenten mit. Einfach loslegen mit der eingebauten Konsole und fertigen Bibliotheken für viele Anwendungsfälle.
Der Talk macht hoffentlich Lust auf mehr und befeuert den/die Maker*in unter euch.

Hardware and Webdeveloper? In this talk I would like to introduce Espruino. The project brings JavaScript to the microcontrollers and makes it possible to implement various projects with little effort. It is not only interesting for tinkerers, but also brings along 'ready to use' components. Just get started with the built-in console and ready-to-use libraries for many use cases.
The talk will hopefully make you curious for more and will fire up the maker inside you.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 09/2020

## Speaker names

Please name all speakers giving this talk.

- Paul Spenke

## Speakers info

(Optional)

## Twitter handle(s)

(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @PaulSpenke

## Other links

- https://github.com/deepDiverPaul

**Comment by martinkutter** [comment]
Talk findet am 29.09.2020 im Q-Hub statt.

**Comment by martinkutter** [comment]
Da hier vermutlich keine Slides mehr kommen, schließe ich für die bessere Übersicht.
