### ISSUE TITLE
Schwarmintelligenz selbst programmieren

### ISSUE THREAD

**Issue by rosemaxio** [ChemnitzerWebDevs/slides#52]
### Titel
**Schwarmintelligenz selbst programmieren**
_Woher weiß Netflix, was ich als nächstes gucken sollte?!_

### Beschreibung

In diesem Vortrag zeige ich, wie die Tech-Giganten den Nutzerschwarm verwenden, um individuelle Empfehlungen zu erzeugen. Auch Netflix, Google und Facebook kochen nur mit Wasser und die Algorithmen sind für jeden Developer verständlich. Nach der Theorie folgt die Praxis: Wir entwicklen live ein Empfehlungssystem für eine Netflix-"Film-Empfehlungen für Dich"-Kategorie. 

### Bild

![88992891_2743210842436716_1526373566738595840_o](https://user-images.githubusercontent.com/70895944/93716389-d6afab80-fb6f-11ea-8d27-9551b901c7f7.jpg)

### Gliederung

- Relevanz von individuellen Empfehlungen in 2020
- Vorstellung KNN Algorithmus
  - Inhalt- vs. nutzerbasiertes Filtern
  - Feature Vektoren
  - Funktionsweise von KNN
  - Ähnliche Nutzer finden
  - Vorschläge erzeugen
- [Praxis] Star Wars Livedemo
- Ethische Fragestellungen
- Weitere Projektideen
  - Empfehlungssystem bei audory
  - Beispiele wie Instagram, Tinder, Amazon, Spotify

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- 29.10.2020

## Speaker names

Please name all speakers giving this talk.

- Max Rose

## Speakers info

(Optional)

- Max Rose, audory, Gründer

## Twitter handle(s)

(Optional, we usually announce speakers via https://twitter.com/webdevchem)

- @webdevchem

## Other links

(Optional, Blog, github, medium, facebook, etc.)

- https://audory.io

**Comment by martinkutter** [comment]
@rosemaxio möchtest du hier noch einen PR mit Folien einreichen?

**Comment by rosemaxio** [comment]
@martinkutter Done #56

**Comment by martinkutter** [comment]
Danke
