### ISSUE TITLE
Kubernetes, Golang & Cluster-API

### ISSUE THREAD

**Issue by guettli** [ChemnitzerWebDevs/slides#57]
## Talk description

This talk gives an introduction to Kubernetes and the programming language behind it (Go).

It will show how to set up a Kubernetes Cluster via Cluster-API on Hetzner.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [x] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x] Yes, maybe
- [ ] No, thanks.

## Preferred date/time

- August 2022 or later

## Speaker names

- Thomas Güttler

## Speakers info

-  https://thomas-guettler.de/

## Twitter handle(s)

- [@guettli](https://twitter.com/guettli)

## Other links

https://go.dev/

**Comment by schroedan** [comment]
@guettli Would you be able to give the talk on 9/29/2022 or is that too short notice?

**Comment by guettli** [comment]
@schroedan November would be good

**Comment by schroedan** [comment]
@gernsdorfer Will get in contact with you.

**Comment by guettli** [comment]
@schroedan I updated the above description of the talk.

**Comment by guettli** [comment]
The slides are online: https://github.com/ChemnitzerWebDevs/slides#2022

I think this issue an get closed now.
