### ISSUE TITLE
Introduction to graph databases, Cypher query language & examples in PHP

### ISSUE THREAD

**Issue by Syndesi** [ChemnitzerWebDevs/slides#61]
## Talk description

Topics of the talk:
- What is a graph database? How do graph databases compare to other types of databases?
- Where can you use graph databases?
- What is [Cypher](https://neo4j.com/developer/cypher/)?
- Examples of plain Cypher.
- Short overview of my PHP graph libraries: [syndesi/cypher-data-structures](https://github.com/neo4j-php/cypher-data-structures) and [syndesi/cypher-entity-manager](https://github.com/neo4j-php/cypher-entity-manager).
- Examples of Cypher in PHP :D

Databases which will be mentioned/used: [Neo4j](https://neo4j.com/) & [Memgraph](https://memgraph.com/).
Frameworks: [Symfony](https://symfony.com/).

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [x] Yes, a practice session would be very helpful :)
- [ ] No, thanks.

## Preferred date/time

- not before February

## Speaker names

- Sören Klein

## Speakers info

- I'm part of the [Neo4j PHP community](https://github.com/neo4j-php)

## Twitter handle(s)

- @webdevchem

## Other links

- [GitHub](https://github.com/Syndesi)

**Comment by schroedan** [comment]
Hi @Syndesi

Thank you for this interesting talk proposal. When could you imagine giving the talk in 2023? Please feel free to contact me if I can help you with the preparations.

**Comment by schroedan** [comment]
Hi @Syndesi 

In all likelihood the meetings will again be held on the last thursday of the month. You are welcome to write to us when your preparations are completed.

**Comment by martinkutter** [comment]
Hey @Syndesi,
could you please provide a teaser image so i can announce your talk for february 23?

**Comment by martinkutter** [comment]
Hey @Syndesi, please keep in mind to send a teaser image. We decided to move to the 02.03. Does that fit for you?

**Comment by Syndesi** [comment]
Hi,
02.03 works for me, thanks :)
Content of the presentation is written out. Formating, design & some fact checks are still work in progress.
Here is the current content of my presentation:

- Quick introduction into database schemes
  - SQL vs NoSQL
- Quick introduction into graph databases
  - History of Graph Databases (1-2 slides, infographics)
  - Classifications of Graph Databases
  - main graph query languages
- Introduction into Cypher
  - explanation of basic syntax, concepts
    - nodes
    - relations
    - properties
    - patterns
    - dynamic length patterns
  - each query has a graphic
  - some queries will be compared to SQL
- Increasing performance
  - benchmark?
  - Index, Constraints
  - Horizontal scaling
  - Data Architecture
  - Polyglot Architecture
  - Debugging Cypher
- Examples, Use-Cases
  - Social Networks
  - Recommendations
  - Fraud detection
  - Digital Twins
  - Knowledge Graphs
- Concrete Example in PHP
- Useful tools, further resources
- Sources
- FAQ

First infographics are nearly done, I'll send you the teaser image this night.

Example infographic:

![infographic graph database history](https://user-images.githubusercontent.com/9903723/218972279-54f302d5-7346-4ffc-bb5f-b50c73faa806.png)

Btw, does the monitor use the 16:9 format?

**Comment by martinkutter** [comment]
@Syndesi yes 16:9 👍🏼

**Comment by Syndesi** [comment]
thanks :)

**Comment by Syndesi** [comment]
Update: I should be able to upload my presentation this evening; I just need to get the ok of some people if they want to be included in the credits.
